#!/bin/sh

set -e

if [ "$1" = "configure" ]; then

	# Create default certificate
    	if [ ! -f /etc/naviserver/default.pem ]; then
        	make-ssl-cert /usr/share/ssl-cert/ssleay.cnf /etc/naviserver/default.pem
    	fi
fi

#DEBHELPER#
