#!/bin/sh -e

case "$1" in
    purge)
	# Remove default certificate if in existence
    	if [ -f /etc/naviserver/default.pem ]; then
         	rm -f /etc/naviserver/default.pem
    	fi

	;;
esac

#DEBHELPER#

exit 0

