#!/bin/sh

set -e

SSL_CERT=/etc/naviserver/default.pem
TEMPLATE=/etc/naviserver/naviserver.cnf

if [ "$1" = "configure" ]; then

	# Create default certificate
    	if [ ! -f $SSL_CERT ]; then
		TMPOUT=`mktemp` || exit 1
		TMPFILE=`mktemp` || exit 1
		if ! HOSTNAME="$(hostname -f)" ; then
			HOSTNAME="$(hostname)"
		fi
		cat <<EOF >$TEMPFILE
#
# Naviserver SSL default cert configuration file.
#

RANDFILE                = /dev/urandom

[ req ]
default_bits            = 2048
default_keyfile         = privkey.pem
distinguished_name      = req_distinguished_name
prompt                  = no
policy			= policy_anything

[ req_distinguished_name ]
commonName                      = $HOSTNAME

EOF

		if ! openssl req -config $TMPFILE -new -x509 -days 3650 -nodes -out $SSL_CERT -keyout $SSL_CERT > $TMPOUT 2>&1 ; then
			echo "Could not create certificate. Openssl output was:" >&2
			cat $TMPOUT >&2
			exit 1
    		fi
    	fi
fi

#DEBHELPER#
